cidades ={
    'SP': ['São paulo', 'São sebastião', 'Taboão da serra', 'São bernardo do campo', 'Limeira', 'Campinas', 'Jau', 'Jarinu', 'Guarulhos', 'Jundiai', 'Osasco', 'Braganca paulista', 'Sao caetano do sul',
         'Marilia', 'Araçariguama', 'Piracicaba', 'Itapecerica da serra', 'Barueri', 'Atibaia', 'Nazare paulista', 'Ilhabela', 'Mogi guacu', 'Bertioga', 'Diadema', 'Santos', 'Cotia', 'Ourinhos',
          'Rio claro', 'Jaguariuna', 'Suzano', 'Santa isabel', 'Carapicuiba', 'Do pinhal', 'Itu', 'Aruja', 'Santo andré', 'Mogi das cruzes', 'Vargem', 'Vinhedo', 'Caieiras', 'Ribeirao pires',
           'São josé do rio preto', 'Jandira', 'Maua', 'Barrinha'], 
           'PR': ['Foz do iguaçu', 'Curitiba', 'Antonina', 'Matelandia', 'Colombo', 'Pinhais', 'Paicandu'], 
           'RJ': ['Duque de caxias', 'Rio de janeiro'], 
           'MG': ['Uberaba', 'Sete lagoas'], 
           'MA': ['Imperatriz', 'Sao luis'], 
           'SC': ['Joinville', 'Blumenau', 'Jaragua do sul', 'Guaramirim', 'Florianopolis', 'Balneario camboriu'], 
           'PA': ['Santo antonio do taua', 'Castanhal'],
           'MS': ['Campo grande', 'Tres lagoas'], 
           'RS': ['Porto alegre'], 
           'PI': ['Teresina'], 
           'CE': ['Sobral'], 
           'RN': ['Natal'], 
           'AM': ['Manaus'], 
           'BA': ['Feira de santana'], 
           'AP': ['Macapa'], 
           'GO': ['Goiania']}